# Allow cookies and headers to pass though Zuul
# Default the sensitiveHeaders (Cookie,Set-Cookie,Authorization) will filter JWT cookie
zuul:
  sensitiveHeaders:

  # Increase timeouts
  host:
    connect-timeout-millis: 60000 # starting the connection
    socket-timeout-millis: 60000  # monitor the continuous incoming data flo